language: node_js
node_js:
- '8'
before_script:
- yarn install
script:
- yarn build
deploy:
  provider: npm
  email: "monkey3310@gmail.com"
  api_key:
    secure: qBQiRFcnW/HtnaUF8NcMkd2s0J75N7o9P1R55GGqT4GFhWGVv9QSvTBsdzTWKdQRFkgmGLVLkt0o/nDE25kuJOj6bVTAdt4HRoTPCcKn00ydT42qUheyO5DCf75LJsZ7hHNWFaXgZ4LHYDySWEMGI28fTdx5Va11OAzlaGoEUoS9PoM6Y+LGJmL/5pA+edcHLDWboXuYctrqfq9/w5X5ZCVl8VtUO3JpuD6vJzNpnPnFYEGxig4iylKPFY3hFOeoS0DKLpa6abC0pfDo+q8bHDs1Z3NilzU6krN+Y2E0rkpS2N+2lx6hxX/O0WZwiYXq9xWhDSHtpfg+kL/EfoQbS393yq8ZhNt78Wd8F1uvUUAJmJ7OaI1hnk+q3CPWrPlf8Vh9nh0rbaqs0AZGFiH5V7Nkjww57cO84TADbP3lxlk1lv08hlALRHtJDovd1feoImh9yklO3x7uisySeX7TRe9qMp7xGs1WDitAWeA5zZcCwpdjnVo4CuPMfftVBv/fiFrJt4rfmwojC2/YlUvZiHCWFt7JiU3cJxK6lajF58/TkEB7E7IURQVh6YHQncOfm7dFHD3i5U6+7N28XUVUHi5uTBpaT1QwDuMW4U7r74OsYfuECUZC542QCCdDuVMFsEN6VWAH+M5Wys0+/z83LFePsIj20f43hwnGraSoh6Q=
  on:
    branch: master
